POST http://localhost:7080/shop/v1/admin/coupons HTTP/1.1
Content-Type: application/json

{
  "name" : "개업 10주년 특별 할인",
  "type" : "정률할인",
  "expiredDate" : 10,
  "minimumMoney" : 20000,
  "discountAmount" : 0.05
}

###

GET http://localhost:7080/shop/v1/admin/coupons/23

###

GET http://localhost:7080/shop/v1/admin/coupons

###

PUT http://localhost:7080/shop/v1/admin/coupons/10 HTTP/1.1
Content-Type: application/json

{
  "name" : "당근 세일",
  "type" : "정액할인",
  "expiredDate" : 10,
  "minimumMoney" : 20000,
  "discountAmount" : 5000
}