POST http://localhost:7080/shop/v1/system/used-coupons HTTP/1.1
Content-Type: application/json

{ "orderId": 1,
  "couponId" : 1,
  "memberId" : 3
}

###

DELETE http://localhost:7080/shop/v1/system/used-coupons HTTP/1.1
Content-Type: application/json

{ "orderId": 1,
  "couponId" : 1,
  "memberId" : 3
}

###